# Translation dictionary (English to Italian)
translation_dict = {
    "builder": "costruttore",
    "captain": "capitano",
    "craftsman": "sovrintendente",
    "governor": "governatore",
    "mayor": "sindaco",
    "prospector": "cercatore d'oro",
    "second_prospector": "cercatore d'oro",
    "settler": "colono",
    "trader": "mercante",

    "coffee": "caffè",
    "corn": "mais",
    "indigo": "indaco",
    "sugar": "zucchero",
    "tobacco": "tabacco",
    
    "city_hall": "municipio",
    "custom_house": "dogana",
    "fortress": "fortezza",
    "guild_hall": "sede della corporazione",
    "residence": "residenza",
    "coffee_roaster": "torrefazione",
    "indigo_plant": "fabbrica di indaco grande",
    "small_indigo_plant": "fabbrica di indaco piccola",
    "small_sugar_mill": "zuccherificio piccolo",
    "sugar_mill": "zuccherificio grande",
    "tobacco_storage": "tabacchificio",
    "construction_hut": "capanna degli attrezzi",
    "factory": "manifattura",
    "hacienda": "hacienda",
    "harbor": "porto",
    "hospice": "ospizio",
    "large_market": "mercato grande",
    "large_warehouse": "magazzino grande",
    "office": "ufficio",
    "small_market": "mercato piccolo",
    "small_warehouse": "magazzino piccolo",
    "university": "università",
    "wharf": "molo",

    "coffee_tile": "tessera caffè",
    "corn_tile": "tessera mais",
    "indigo_tile": "tessera indaco",
    "quarry_tile": "cava",
    "sugar_tile": "tessera zucchero",
    "tobacco_tile": "tessera tabacco",
}

# Explanation dictionary (English to Italian explanation)
explanation_dict = {
    "builder": "Permette di costruire un palazzo, pagando un doblone in meno.",
    "captain": "Bisogna caricare le merci sulle navi per ottenere punti vittoria. Il capitano ottiene 1 PV extra.",
    "craftsman": "Permette di produrre merci in base alle piantagioni occupate. L'artigiano ottiene 1 merce in più.",
    "governor": "Inizia il round scegliendo un ruolo.",
    "mayor": "Permette di prendere coloni e piazzarli sui cerchietti vuoti dei segnalini. Il sindaco ottiene 1 colono extra.",
    "settler": "Permette di piazzare un nuovo segnalino piantagione o cava sull'isola. Il colonizzatore può prendere una cava invece di una piantagione.",
    "trader": "Permette di vendere una merce all'emporio. Il commerciante ottiene 1 doblone extra.",
    "prospector": "Prende un doblone dalla banca.",
    "second_prospector": "Prende un doblone dalla banca.",
    "city_hall": "Palazzo grande. Vale 4 PV più 1 per ogni palazzo viola occupato nella città, incluso se stesso.",
    "custom_house": "Palazzo grande. Vale 4 PV più 1 PV ogni 4 PV ottenuti (dai gettoni, non dai palazzi).",
    "fortress": "Palazzo grande. Vale 4 PV più 1 PV ogni 3 coloni sulla scheda del giocatore.",
    "guild_hall": "Palazzo grande. Vale 4 PV più 1 PV per ogni impianto di produzione piccolo e 2 PV per ogni impianto grande nella città.",
    "residence": "Palazzo grande. Vale 4 PV più bonus in base al numero di segnalini sull'isola: 9 = +4 PV, 10 = +5 PV, 11 = +6 PV, 12 = +7 PV.",
    "coffee_roaster": "Impianto di produzione. Serve per produrre caffè dalle piantagioni di caffè.",
    "indigo_plant": "Impianto di produzione. Serve per produrre indaco dalle piantagioni di indaco.",
    "small_indigo_plant": "Impianto di produzione piccolo. Serve per produrre indaco dalle piantagioni di indaco.",
    "small_sugar_mill": "Impianto di produzione piccolo. Serve per produrre zucchero dalle piantagioni di zucchero.",
    "sugar_mill": "Impianto di produzione. Serve per produrre zucchero dalle piantagioni di zucchero.",
    "tobacco_storage": "Impianto di produzione. Serve per produrre tabacco dalle piantagioni di tabacco.",
    "construction_hut": "Piccolo palazzo. Permette di prendere una cava invece di una piantagione nella fase del colonizzatore.",
    "factory": "Piccolo palazzo. Il proprietario ottiene dobloni in base al numero di tipi di merce prodotti.",
    "hacienda": "Piccolo palazzo. Permette di prendere una piantagione extra dalla pila coperta nella fase del colonizzatore.",
    "harbor": "Piccolo palazzo. Il proprietario ottiene 1 PV extra ogni volta che carica merci sulle navi.",
    "hospice": "Piccolo palazzo. Permette di prendere un colono dalla riserva quando si piazza una nuova piantagione o cava.",
    "large_market": "Piccolo palazzo. Il proprietario ottiene 2 dobloni extra quando vende una merce all'emporio.",
    "large_warehouse": "Piccolo palazzo. Permette di conservare due tipi di merce extra dopo la fase del capitano.",
    "office": "Piccolo palazzo. Permette di vendere una merce già presente nell'emporio. Costa 5 dobloni, occupa 1 lavoratore, vale 2 punti.",
    "small_market": "Piccolo palazzo. Il proprietario ottiene 1 doblone extra quando vende una merce all'emporio.",
    "small_warehouse": "Piccolo palazzo. Permette di conservare un tipo di merce extra dopo la fase del capitano.",
    "university": "Piccolo palazzo. Permette di prendere un colono dalla riserva quando si costruisce un palazzo.",
    "wharf": "Piccolo palazzo. Permette di 'caricare' tutte le merci di un tipo nella riserva come se fossero su una nave, guadagnando i relativi PV.",
}