import pytest
from game.bots.rufus import Rufus
# from rich import print
from game import *


def test_rufus():
    names = ["Ada", "Bert", "Carl", "Dan"]
    game = Game.start_new(names)
    game.people = 32  # Shorter game
    bots = {name: Rufus(name=name) for name in game.play_order}
    state, action = game.compress(), None
    while True:
        try:
            prev_state = state
            state, prev_action = game.compress(), action.model_dump() if action else None
            action = bots[game.expected_player.name].decide(game)
            game.take_action(action)
        except GameOver as reason:
            print(reason)
            print("Final score")
            scores = {player.name: player.tally() for player in game.players.values()}
            for name, score in scores.items():
                print("  ", name, ">", score, "points")
            break
        except Exception as err:
            breakpoint()
            raise err


def test_01():
    game = Game(
        money=42,
        people=75,
        points=122,
        coffee=9,
        corn=10,
        indigo=11,
        sugar=11,
        tobacco=9,
        players={
            "Bot Ada": Player(
                money=3,
                people=0,
                points=0,
                coffee=0,
                corn=0,
                indigo=0,
                sugar=0,
                tobacco=0,
                name="Bot Ada",
                pseudo="BA",
                gov=False,
                role=Role(
                    money=0,
                    people=0,
                    points=0,
                    coffee=0,
                    corn=0,
                    indigo=0,
                    sugar=0,
                    tobacco=0,
                    type="trader",
                ),
                tiles=[
                    Tile(
                        money=0,
                        people=0,
                        points=0,
                        coffee=0,
                        corn=0,
                        indigo=0,
                        sugar=0,
                        tobacco=0,
                        type="indigo",
                    ),
                    Tile(
                        money=0,
                        people=0,
                        points=0,
                        coffee=0,
                        corn=0,
                        indigo=0,
                        sugar=0,
                        tobacco=0,
                        type="tobacco",
                    ),
                ],
                buildings=[],
            ),
            "Bot Bert": Player(
                money=3,
                people=0,
                points=0,
                coffee=0,
                corn=0,
                indigo=0,
                sugar=0,
                tobacco=0,
                name="Bot Bert",
                pseudo="BB",
                gov=True,
                role=Role(
                    money=0,
                    people=0,
                    points=0,
                    coffee=0,
                    corn=0,
                    indigo=0,
                    sugar=0,
                    tobacco=0,
                    type="settler",
                ),
                tiles=[
                    Tile(
                        money=0,
                        people=0,
                        points=0,
                        coffee=0,
                        corn=0,
                        indigo=0,
                        sugar=0,
                        tobacco=0,
                        type="indigo",
                    ),
                    Tile(
                        money=0,
                        people=0,
                        points=0,
                        coffee=0,
                        corn=0,
                        indigo=0,
                        sugar=0,
                        tobacco=0,
                        type="quarry",
                    ),
                ],
                buildings=[],
            ),
            "Bot Carl": Player(
                money=3,
                people=0,
                points=0,
                coffee=0,
                corn=0,
                indigo=0,
                sugar=0,
                tobacco=0,
                name="Bot Carl",
                pseudo="BC",
                gov=False,
                role=None,
                tiles=[
                    Tile(
                        money=0,
                        people=0,
                        points=0,
                        coffee=0,
                        corn=0,
                        indigo=0,
                        sugar=0,
                        tobacco=0,
                        type="corn",
                    ),
                    Tile(
                        money=0,
                        people=0,
                        points=0,
                        coffee=0,
                        corn=0,
                        indigo=0,
                        sugar=0,
                        tobacco=0,
                        type="sugar",
                    ),
                ],
                buildings=[],
            ),
            "Bot Dan": Player(
                money=3,
                people=0,
                points=0,
                coffee=0,
                corn=0,
                indigo=0,
                sugar=0,
                tobacco=0,
                name="Bot Dan",
                pseudo="BD",
                gov=False,
                role=None,
                tiles=[
                    Tile(
                        money=0,
                        people=0,
                        points=0,
                        coffee=0,
                        corn=0,
                        indigo=0,
                        sugar=0,
                        tobacco=0,
                        type="corn",
                    ),
                    Tile(
                        money=0,
                        people=0,
                        points=0,
                        coffee=0,
                        corn=0,
                        indigo=0,
                        sugar=0,
                        tobacco=0,
                        type="tobacco",
                    ),
                ],
                buildings=[],
            ),
        },
        play_order=["Bot Bert", "Bot Ada", "Bot Carl", "Bot Dan"],
        actions=[
            Action(type="trader", player_name="Bot Ada"),
            Action(type="trader", player_name="Bot Carl"),
            Action(type="trader", player_name="Bot Dan"),
            Action(type="trader", player_name="Bot Bert"),
            Action(type="role", player_name="Bot Carl"),
            Action(type="role", player_name="Bot Dan"),
            GovernorAction(type="governor", player_name="Bot Ada"),
            GovernorAction(type="governor", player_name="Bot Carl"),
            GovernorAction(type="governor", player_name="Bot Dan"),
            GovernorAction(type="governor", player_name="Bot Bert"),
        ],
        people_ship=Holder(
            money=0, people=4, points=0, coffee=0, corn=0, indigo=0, sugar=0, tobacco=0
        ),
        goods_ships={
            5: Holder(
                money=0,
                people=0,
                points=0,
                coffee=0,
                corn=0,
                indigo=0,
                sugar=0,
                tobacco=0,
            ),
            6: Holder(
                money=0,
                people=0,
                points=0,
                coffee=0,
                corn=0,
                indigo=0,
                sugar=0,
                tobacco=0,
            ),
            7: Holder(
                money=0,
                people=0,
                points=0,
                coffee=0,
                corn=0,
                indigo=0,
                sugar=0,
                tobacco=0,
            ),
        },
        market=Holder(
            money=0, people=0, points=0, coffee=0, corn=0, indigo=0, sugar=0, tobacco=0
        ),
        roles=[
            Role(
                money=0,
                people=0,
                points=0,
                coffee=0,
                corn=0,
                indigo=0,
                sugar=0,
                tobacco=0,
                type="builder",
            ),
            Role(
                money=0,
                people=0,
                points=0,
                coffee=0,
                corn=0,
                indigo=0,
                sugar=0,
                tobacco=0,
                type="captain",
            ),
            Role(
                money=0,
                people=0,
                points=0,
                coffee=0,
                corn=0,
                indigo=0,
                sugar=0,
                tobacco=0,
                type="craftsman",
            ),
            Role(
                money=0,
                people=0,
                points=0,
                coffee=0,
                corn=0,
                indigo=0,
                sugar=0,
                tobacco=0,
                type="mayor",
            ),
            Role(
                money=0,
                people=0,
                points=0,
                coffee=0,
                corn=0,
                indigo=0,
                sugar=0,
                tobacco=0,
                type="prospector",
            ),
        ],
        unsettled_quarries=7,
        unsettled_tiles=[
            "tobacco",
            "indigo",
            "indigo",
            "sugar",
            "indigo",
            "indigo",
            "sugar",
            "tobacco",
            "indigo",
            "sugar",
            "corn",
            "indigo",
            "coffee",
            "corn",
            "sugar",
            "coffee",
            "indigo",
            "tobacco",
            "corn",
            "sugar",
            "sugar",
            "tobacco",
            "corn",
            "tobacco",
            "corn",
            "coffee",
            "sugar",
            "corn",
            "corn",
            "indigo",
            "indigo",
            "indigo",
            "sugar",
            "sugar",
            "tobacco",
            "corn",
            "coffee",
            "coffee",
        ],
        exposed_tiles=["coffee", "coffee", "tobacco", "sugar", "coffee"],
        unbuilt=[
            "indigo_plant",
            "indigo_plant",
            "indigo_plant",
            "small_indigo_plant",
            "small_indigo_plant",
            "small_indigo_plant",
            "small_indigo_plant",
            "sugar_mill",
            "sugar_mill",
            "sugar_mill",
            "small_sugar_mill",
            "small_sugar_mill",
            "small_sugar_mill",
            "small_sugar_mill",
            "tobacco_storage",
            "tobacco_storage",
            "tobacco_storage",
            "coffee_roaster",
            "coffee_roaster",
            "coffee_roaster",
            "small_market",
            "small_market",
            "hacienda",
            "hacienda",
            "construction_hut",
            "construction_hut",
            "small_warehouse",
            "small_warehouse",
            "hospice",
            "hospice",
            "office",
            "office",
            "large_market",
            "large_market",
            "large_warehouse",
            "large_warehouse",
            "factory",
            "factory",
            "university",
            "university",
            "harbor",
            "harbor",
            "wharf",
            "wharf",
            "guild_hall",
            "residence",
            "fortress",
            "city_hall",
            "custom_house",
        ],
    )
    bots = {name: Rufus(name=name) for name in game.play_order}
    action = bots[game.expected_player.name].decide(game)
    assert action.type == "refuse"


def test_02():
    game = Game.from_compressed(
        {
            "actions": [
                "settler:Ada",
                "settler:Carl",
                "settler:Dan",
                "settler:Bert",
                "role:Carl",
                "role:Dan",
                "governor:Ada",
                "governor:Carl",
                "governor:Dan",
                "governor:Bert",
            ],
            "exposed_tiles": ["corn", "sugar", "sugar", "indigo", "indigo"],
            "goods_ships": {5: "", 6: "", 7: ""},
            "holding": "c9i9m45w24p122s4t9",
            "market": "k1",
            "people_ship": "w10",
            "play_order": ["Ada", "Carl", "Dan", "Bert"],
            "players": {
                "Ada": {
                    "info": "human:Ad:settler:000",
                    "holding": "m1w3",
                    "tiles": [
                        "indigo:1",
                        "tobacco:0",
                        "sugar:1",
                        "tobacco:1",
                        "coffee:0",
                        "indigo:1",
                        "indigo:0",
                    ],
                    "buildings": [
                        "hospice:1",
                        "large_warehouse:0",
                        "small_warehouse:1",
                        "indigo_plant:0",
                    ],
                },
                "Bert": {
                    "info": "human:Be:prospector:100",
                    "holding": "k4m3w7s1",
                    "tiles": [
                        "corn:1",
                        "sugar:1",
                        "corn:1",
                        "quarry:0",
                        "corn:1",
                        "tobacco:0",
                        "coffee:0",
                        "indigo:0",
                    ],
                    "buildings": [
                        "small_indigo_plant:0",
                        "small_sugar_mill:1",
                        "hacienda:1",
                        "construction_hut:0",
                        "small_warehouse:0",
                        "small_indigo_plant:0",
                    ],
                },
                "Carl": {
                    "info": "human:Ca::000",
                    "holding": "i2m1w8",
                    "tiles": [
                        "indigo:1",
                        "indigo:1",
                        "coffee:1",
                        "tobacco:0",
                        "sugar:0",
                        "quarry:0",
                        "corn:0",
                    ],
                    "buildings": [
                        "hospice:0",
                        "small_market:0",
                        "small_indigo_plant:1",
                        "small_sugar_mill:0",
                    ],
                },
                "Dan": {
                    "info": "human:Da::000",
                    "holding": "k5w3s6",
                    "tiles": [
                        "corn:0",
                        "coffee:0",
                        "tobacco:0",
                        "coffee:1",
                        "sugar:1",
                        "sugar:1",
                        "corn:1",
                        "sugar:0",
                    ],
                    "buildings": [
                        "small_market:0",
                        "small_indigo_plant:0",
                        "sugar_mill:2",
                        "construction_hut:1",
                        "large_market:0",
                        "hacienda:1",
                        "small_sugar_mill:0",
                    ],
                },
            },
            "roles": ["mayor:2", "captain:1", "trader:1", "builder:0", "craftsman:0"],
            "unbuilt": [
                "indigo_plant",
                "indigo_plant",
                "sugar_mill",
                "sugar_mill",
                "small_sugar_mill",
                "tobacco_storage",
                "tobacco_storage",
                "tobacco_storage",
                "coffee_roaster",
                "coffee_roaster",
                "coffee_roaster",
                "office",
                "office",
                "large_market",
                "large_warehouse",
                "factory",
                "factory",
                "university",
                "university",
                "harbor",
                "harbor",
                "wharf",
                "wharf",
                "guild_hall",
                "residence",
                "fortress",
                "city_hall",
                "custom_house",
            ],
            "unsettled_quarries": 6,
            "unsettled_tiles": [
                "sugar",
                "tobacco",
                "tobacco",
                "corn",
                "tobacco",
                "coffee",
                "indigo",
                "indigo",
                "sugar",
                "corn",
                "coffee",
                "indigo",
                "tobacco",
                "coffee",
                "indigo",
                "sugar",
                "corn",
            ],
        }
    )
    action = SettlerAction(
        type="settler",
        player_name="Ada",
        tile="corn",
        down_tile=False,
        extra_person=True,
    )
    game.take_action(action)

def test_03():
    names = ["Ada", "Bert", "Carl", "Dan"]
    intelligences = ["human", "rufus", "rufus", "rufus"]
    game = Game.start_new(users=names, intelligences=intelligences)
    assert game.expected_player.name == "Ada"
    action = Rufus("Ada").decide(game)
    game.take_action(action)
    assert game.expected_player.name == "Ada"

